exclude: [".rvmrc", ".rbenv-version", "ReadMe.md", "Rakefile", "changelog.md", "License.md"]
highlighter: rouge

title : LaGriT
author :
  name : Nathaniel Knapp
  email : nknapp@lanl.gov
  github : deknapp

production_url : https://lanl.github.io/LaGriT

base_url : https://lanl.github.io/LaGriT

markdown: kramdown

