exclude: [".rvmrc", ".rbenv-version", "ReadMe.md", "Rakefile", "changelog.md", "License.md"]
highlighter: rouge

# Themes are encouraged to use these universal variables
# so be sure to set them if your theme uses them.
#
title : LaGriT
author :
  name : Nathaniel Knapp
  email : nknapp@lanl.gov
  github : deknapp

# NOTE: If replacing this next line with your own URL, you likely want "https://" not "http://"
production_url : http://lanl.github.io/LaGriT

# Tell Github to use the kramdown markdown interpreter
# (see https://help.github.com/articles/migrating-your-pages-site-from-maruku)
markdown: kramdown

# All Jekyll-Bootstrap specific configurations are namespaced into this hash
#
JB :
  version : 0.3.0
