permalink: /:categories/:year/:month/:day/:title
exclude: [".rvmrc", ".rbenv-version", "ReadMe.md", "Rakefile", "changelog.md", "License.md"]
highlighter: rouge

title : LaGriT
author :
  name : Nathaniel Knapp
  email : nknapp@lanl.gov
  github : deknapp

production_url : https://lanl.github.io/LaGriT

markdown: kramdown

kramdown:
  input: GFM
  hard_wrap: false
  
JB :
  version : 0.3.0

sass:
    sass_dir: _sass
    style: compressed
