permalink: /:categories/:year/:month/:day/:title
exclude: [".rvmrc", ".rbenv-version", "ReadMe.md", "Rakefile", "changelog.md", "License.md"]
highlighter: rouge

title : LaGriT
author :
  name : Nathaniel Knapp
  email : nathaniel.knapp@gmail.com
  github : deknapp

url: "http://lanl.github.io/LaGriT"
baseurl: ""
production_url: "https://lanl.github.io/LaGriT"

JB :
  version : 0.3.0

markdown: kramdown

kramdown:
  input: GFM
  hard_wrap: false
 
sass:
  sass_dir: _sass
  style: compressed
    
   


