exclude: [".rvmrc", ".rbenv-version", "ReadMe.md", "Rakefile", "changelog.md", "License.md"]
highlighter: rouge

title : LaGriT
author :
  name : Nathaniel Knapp
  email : nknapp@lanl.gov
  github : deknapp

theme: jekyll-theme-slate

production_url : https://lanl.github.io/LaGriT

base_url : https://lanl.github.io/LaGriT

kramdown:
   input: GFM
   hard_wrap: false

gems: [jekyll-sitemap]

plugins:
  - jekyll-sitemap


